const movies = [
  {
    id: "1",
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama"],
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency in a corrupt 1940s-era prison.",
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    runtime: 142,
    rated: "R",
    language: "English",
    country: "USA",
    awards: "Nominated for 7 Oscars",
    imdbRating: 9.3,
    boxOffice: "$16,000,000",
  },
  {
    id: "2",
    title: "Blade Runner 2049",
    year: 2017,
    genre: ["Sci-Fi", "Drama", "Action"],
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Jared Leto"],
    plot: "A young blade runner discovers a long-buried secret that has the potential to plunge what's left of society into chaos.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    runtime: 164,
    rated: "R",
    language: "English, Finnish, Hungarian",
    country: "USA, UK, Hungary",
    awards: "Won 2 Oscars",
    imdbRating: 8.0,
    boxOffice: "$92,054,159",
  },
  {
    id: "3",
    title: "The Dark Knight",
    year: 2008,
    genre: ["Crime", "Action", "Drama"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    plot: "When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    runtime: 152,
    rated: "PG-13",
    language: "English",
    country: "USA, UK",
    awards: "Won 2 Oscars",
    imdbRating: 9.0,
    boxOffice: "$534,858,444",
  },
  {
    id: "4",
    title: "Inception",
    year: 2010,
    genre: ["Thriller", "Sci-Fi", "Action"],
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    plot: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into a CEO's mind.",
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    runtime: 148,
    rated: "PG-13",
    language: "English, Japanese, French",
    country: "USA, UK",
    awards: "Won 4 Oscars",
    imdbRating: 8.8,
    boxOffice: "$292,576,195",
  },
  {
    id: "5",
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    runtime: 169,
    rated: "PG-13",
    language: "English",
    country: "USA, UK",
    awards: "Won 1 Oscar",
    imdbRating: 8.7,
    boxOffice: "$188,020,017",
  },
  {
    id: "6",
    title: "Parasite",
    year: 2019,
    genre: ["Comedy", "Drama", "Thriller"],
    director: "Bong Joon Ho",
    cast: ["Kang-ho Song", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    runtime: 132,
    rated: "R",
    language: "Korean",
    country: "South Korea",
    awards: "Won 4 Oscars",
    imdbRating: 8.5,
    boxOffice: "$53,369,749",
  },
  {
    id: "7",
    title: "Fight Club",
    year: 1999,
    genre: ["Drama", "Thriller"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much more.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    runtime: 139,
    rated: "R",
    language: "English",
    country: "USA, Germany",
    awards: "Nominated for 1 Oscar",
    imdbRating: 8.8,
    boxOffice: "$37,030,102",
  },
  {
    id: "8",
    title: "Forrest Gump",
    year: 1994,
    genre: ["Romance", "Drama"],
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    plot: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an extraordinary destiny.",
    poster: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    runtime: 142,
    rated: "PG-13",
    language: "English",
    country: "USA",
    awards: "Won 6 Oscars",
    imdbRating: 8.8,
    boxOffice: "$330,455,270",
  },
  {
    id: "9",
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    director: "Lana Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    plot: "A hacker discovers the shocking truth — the life he knows is the elaborate deception of an evil cyber-intelligence.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    runtime: 136,
    rated: "R",
    language: "English",
    country: "USA, Australia",
    awards: "Won 4 Oscars",
    imdbRating: 8.7,
    boxOffice: "$171,479,930",
  },
  {
    id: "10",
    title: "Se7en",
    year: 1995,
    genre: ["Mystery", "Drama", "Crime"],
    director: "David Fincher",
    cast: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey", "Gwyneth Paltrow"],
    plot: "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    runtime: 127,
    rated: "R",
    language: "English",
    country: "USA",
    awards: "Nominated for 1 Oscar",
    imdbRating: 8.6,
    boxOffice: "$100,125,643",
  },
  // {
  //   id: "11",
  //   title: "The Lord of the Rings: The Fellowship of the Ring",
  //   year: 2001,
  //   genre: ["Adventure", "Fantasy"],
  //   director: "Peter Jackson",
  //   cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Viggo Mortensen"],
  //   plot: "A hobbit and eight companions set out to destroy the One Ring and save Middle-earth from the Dark Lord Sauron.",
  //   poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
  //   runtime: 178,
  //   rated: "PG-13",
  //   language: "English",
  //   country: "New Zealand, USA",
  //   awards: "Won 4 Oscars",
  //   imdbRating: 8.8,
  //   boxOffice: "$315,544,750",
  // },
  // {
  //   id: "12",
  //   title: "The Return of the King",
  //   year: 2003,
  //   genre: ["Action", "Adventure", "Fantasy"],
  //   director: "Peter Jackson",
  //   cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Andy Serkis"],
  //   plot: "Gandalf and Aragorn lead the World of Men against Sauron while Frodo and Sam approach Mount Doom with the One Ring.",
  //   poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  //   runtime: 201,
  //   rated: "PG-13",
  //   language: "English",
  //   country: "New Zealand, USA",
  //   awards: "Won 11 Oscars",
  //   imdbRating: 9.0,
  //   boxOffice: "$377,845,905",
  // },
  // {
  //   id: "13",
  //   title: "Pulp Fiction",
  //   year: 1994,
  //   genre: ["Crime", "Drama"],
  //   director: "Quentin Tarantino",
  //   cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
  //   plot: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
  //   poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  //   runtime: 154,
  //   rated: "R",
  //   language: "English, Spanish, French",
  //   country: "USA",
  //   awards: "Won 1 Oscar",
  //   imdbRating: 8.9,
  //   boxOffice: "$107,928,762",
  // },
  // {
  //   id: "14",
  //   title: "Goodfellas",
  //   year: 1990,
  //   genre: ["Biography", "Crime", "Drama"],
  //   director: "Martin Scorsese",
  //   cast: ["Ray Liotta", "Robert De Niro", "Joe Pesci", "Lorraine Bracco"],
  //   plot: "The story of Henry Hill and his life in the mob, covering his relationship with his mob partners and his eventual downfall.",
  //   poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
  //   runtime: 146,
  //   rated: "R",
  //   language: "English",
  //   country: "USA",
  //   awards: "Won 1 Oscar",
  //   imdbRating: 8.7,
  //   boxOffice: "$46,836,394",
  // },
  // {
  //   id: "15",
  //   title: "Spirited Away",
  //   year: 2001,
  //   genre: ["Animation", "Adventure", "Fantasy"],
  //   director: "Hayao Miyazaki",
  //   cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino", "Rumi Hiiragi"],
  //   plot: "A sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and must find a way to free herself and her parents.",
  //   poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  //   runtime: 125,
  //   rated: "PG",
  //   language: "Japanese",
  //   country: "Japan",
  //   awards: "Won 1 Oscar",
  //   imdbRating: 8.6,
  //   boxOffice: "$10,055,859",
  // },
  // {
  //   id: "16",
  //   title: "Schindler's List",
  //   year: 1993,
  //   genre: ["Biography", "Drama", "History"],
  //   director: "Steven Spielberg",
  //   cast: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley", "Caroline Goodall"],
  //   plot: "Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis in German-occupied Poland.",
  //   poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
  //   runtime: 195,
  //   rated: "R",
  //   language: "English, Hebrew, German",
  //   country: "USA",
  //   awards: "Won 7 Oscars",
  //   imdbRating: 9.0,
  //   boxOffice: "$96,898,818",
  // },
  // {
  //   id: "17",
  //   title: "The Silence of the Lambs",
  //   year: 1991,
  //   genre: ["Crime", "Drama", "Thriller"],
  //   director: "Jonathan Demme",
  //   cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
  //   plot: "A young FBI cadet must receive the help of an incarcerated cannibalistic serial killer to catch another serial killer.",
  //   poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
  //   runtime: 118,
  //   rated: "R",
  //   language: "English",
  //   country: "USA",
  //   awards: "Won 5 Oscars",
  //   imdbRating: 8.6,
  //   boxOffice: "$130,742,922",
  // },
  // {
  //   id: "18",
  //   title: "Whiplash",
  //   year: 2014,
  //   genre: ["Drama", "Music"],
  //   director: "Damien Chazelle",
  //   cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist", "Paul Reiser"],
  //   plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an abusive instructor.",
  //   poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
  //   runtime: 107,
  //   rated: "R",
  //   language: "English",
  //   country: "USA",
  //   awards: "Won 3 Oscars",
  //   imdbRating: 8.5,
  //   boxOffice: "$13,092,000",
  // },
  // {
  //   id: "19",
  //   title: "The Grand Budapest Hotel",
  //   year: 2014,
  //   genre: ["Adventure", "Comedy", "Drama"],
  //   director: "Wes Anderson",
  //   cast: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan", "Bill Murray"],
  //   plot: "A writer encounters the owner of an aging European hotel and hears the story of the legendary concierge who once ran it.",
  //   poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
  //   runtime: 99,
  //   rated: "R",
  //   language: "English, French, German",
  //   country: "Germany, UK",
  //   awards: "Won 4 Oscars",
  //   imdbRating: 8.1,
  //   boxOffice: "$59,301,324",
  // },
  // {
  //   id: "20",
  //   title: "The Godfather",
  //   year: 1972,
  //   genre: ["Crime", "Drama"],
  //   director: "Francis Ford Coppola",
  //   cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
  //   plot: "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant youngest son.",
  //   poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLS1yekAc5ng.jpg",
  //   runtime: 175,
  //   rated: "R",
  //   language: "English, Italian",
  //   country: "USA",
  //   awards: "Won 3 Oscars",
  //   imdbRating: 9.2,
  //   boxOffice: "$134,966,411",
  // },
  
];

export default movies;