const movies = [
  {
    imdbID: "tt0111161",
    Title: "The Shawshank Redemption",
    Year: "1994",
    Genre: "Drama",
    Director: "Frank Darabont",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency in a corrupt 1940s-era prison.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
    imdbRating: "9.3",
    Runtime: "142 min",
    Awards: "Nominated for 7 Oscars.",
    Rated: "R",
    BoxOffice: "$16,000,000",
    Language: "English",
    Country: "USA",
  },
  {
    imdbID: "tt0068646",
    Title: "The Godfather",
    Year: "1972",
    Genre: "Crime, Drama",
    Director: "Francis Ford Coppola",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "9.2",
    Runtime: "175 min",
    Awards: "Won 3 Oscars.",
    Rated: "R",
    BoxOffice: "$134,966,411",
    Language: "English, Italian",
    Country: "USA",
  },
  {
    imdbID: "tt0468569",
    Title: "The Dark Knight",
    Year: "2008",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    imdbRating: "9.0",
    Runtime: "152 min",
    Awards: "Won 2 Oscars.",
    Rated: "PG-13",
    BoxOffice: "$534,858,444",
    Language: "English, Mandarin",
    Country: "USA, UK",
  },
  {
    imdbID: "tt1375666",
    Title: "Inception",
    Year: "2010",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    imdbRating: "8.8",
    Runtime: "148 min",
    Awards: "Won 4 Oscars.",
    Rated: "PG-13",
    BoxOffice: "$292,576,195",
    Language: "English, Japanese, French",
    Country: "USA, UK",
  },
  {
    imdbID: "tt0816692",
    Title: "Interstellar",
    Year: "2014",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    imdbRating: "8.7",
    Runtime: "169 min",
    Awards: "Won 1 Oscar.",
    Rated: "PG-13",
    BoxOffice: "$188,020,017",
    Language: "English",
    Country: "USA, UK",
  },
  {
    imdbID: "tt6751668",
    Title: "Parasite",
    Year: "2019",
    Genre: "Comedy, Drama, Thriller",
    Director: "Bong Joon Ho",
    Actors: "Kang-ho Song, Lee Sun-kyun, Cho Yeo-jeong",
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    imdbRating: "8.5",
    Runtime: "132 min",
    Awards: "Won 4 Oscars.",
    Rated: "R",
    BoxOffice: "$53,369,749",
    Language: "Korean, English",
    Country: "South Korea",
  },
  {
    imdbID: "tt0137523",
    Title: "Fight Club",
    Year: "1999",
    Genre: "Drama",
    Director: "David Fincher",
    Actors: "Brad Pitt, Edward Norton, Meat Loaf",
    Plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    imdbRating: "8.8",
    Runtime: "139 min",
    Awards: "Nominated for 1 Oscar.",
    Rated: "R",
    BoxOffice: "$37,030,102",
    Language: "English",
    Country: "Germany, USA",
  },
  {
    imdbID: "tt0109830",
    Title: "Forrest Gump",
    Year: "1994",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Actors: "Tom Hanks, Robin Wright, Gary Sinise",
    Plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective of an Alabama man.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    imdbRating: "8.8",
    Runtime: "142 min",
    Awards: "Won 6 Oscars.",
    Rated: "PG-13",
    BoxOffice: "$330,455,270",
    Language: "English",
    Country: "USA",
  },
  {
    imdbID: "tt0133093",
    Title: "The Matrix",
    Year: "1999",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth—the life he knows is the elaborate deception of an evil cyber-intelligence.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVlLTM5YTUtZWU4M2ZlNWVlMzA4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.7",
    Runtime: "136 min",
    Awards: "Won 4 Oscars.",
    Rated: "R",
    BoxOffice: "$171,479,930",
    Language: "English",
    Country: "USA, Australia",
  },
  {
    imdbID: "tt0114369",
    Title: "Se7en",
    Year: "1995",
    Genre: "Crime, Drama, Mystery",
    Director: "David Fincher",
    Actors: "Morgan Freeman, Brad Pitt, Kevin Spacey",
    Plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    imdbRating: "8.6",
    Runtime: "127 min",
    Awards: "Nominated for 1 Oscar.",
    Rated: "R",
    BoxOffice: "$100,125,643",
    Language: "English",
    Country: "USA",
  },
  {
    imdbID: "tt0120737",
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Year: "2001",
    Genre: "Adventure, Drama, Fantasy",
    Director: "Peter Jackson",
    Actors: "Elijah Wood, Ian McKellen, Orlando Bloom",
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    imdbRating: "8.8",
    Runtime: "178 min",
    Awards: "Won 4 Oscars.",
    Rated: "PG-13",
    BoxOffice: "$315,544,750",
    Language: "English, Sindarin",
    Country: "New Zealand, USA",
  },
  {
    imdbID: "tt0167260",
    Title: "The Lord of the Rings: The Return of the King",
    Year: "2003",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDJhZWMtODU5NS00NTExLWI1NjMtZjRlYWIxM2Y2ZWYwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "9.0",
    Runtime: "201 min",
    Awards: "Won 11 Oscars.",
    Rated: "PG-13",
    BoxOffice: "$377,845,905",
    Language: "English, Quenya, Old English",
    Country: "New Zealand, USA",
  },
];

export default movies;
